export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const NEXT_TRACK = "NEXT_TRACK";
export const PREV_TRACK = "PREV_TRACK";
export const TOGGLE_SUFFLED = "TOGGLE_SUFFLED";
export const AUTO_NEXT_TRACK = "AUTO_NEXT_TRACK";
